I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\Beller\Documents\Ren'Py\ImaginaryFriends\game/imaginary_friends_logic.rpy.
  File "game/imaginary_friends_logic.rpy", line 20, in <module>
    now = night_star
NameError: name 'night_star' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\main.py", line 490, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\script.py", line 297, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\script.py", line 809, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\script.py", line 499, in finish_load
    node.early_execute()
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\ast.py", line 1188, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/imaginary_friends_logic.rpy", line 20, in <module>
    now = night_star
NameError: name 'night_star' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
 
Sat Apr 22 08:46:45 2023
