I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/imaginary_friends_variables.rpy", line 46, in set_default
    default friends_stats = {
  File "game/imaginary_friends_variables.rpy", line 47, in <module>
    Char1 : 100,
NameError: name 'Char1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\exports.py", line 3797, in execute_default_statement
    i.set_default(start)
  File "game/imaginary_friends_variables.rpy", line 46, in set_default
    default friends_stats = {
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/imaginary_friends_variables.rpy", line 47, in <module>
    Char1 : 100,
NameError: name 'Char1' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Imaginary Friends 1.0
Sat Apr  1 09:39:12 2023
